all: energy

energy: ma mah mahRatio

mahAverage:
	python3 ./mahBargraphAverage.py

mah:
	python3 ./mahBargraph.py

ma:
	python3 ./maBargraph.py

mahRatio:
	python3 ./mahRatio.py

mahRatioAverage:
	python3 ./mahRatioAverage.py

network: tp tpAvg tpRatio tpRatioAvg packetLoss averageloss

tp:
	python3 ./throughput.py

tpAvg:
	python3 ./throughputAverage.py

tpRatio:
	python3 ./throughputRatio.py

tpRatioAvg:
	python3 ./throughputRatioAverage.py

packetloss:
	python3 ./packetloss.py

averageloss:
	python3 ./packetlossAverage.py