all: energy throughput

energy: ma mah

mahAverage:
	python3 ./mahBargraphAverage.py

mah:
	python3 ./mahBargraph.py

ma:
	python3 ./maBargraph.py

# python3 ./bargraph.py
# python3 ./bargraph-mA.py
# python3 ./bargraph-average.py
# python3 ./linegraph.py
# python3 ./linegraph-average.py

# throughput:
# 	python3 ./throughput.py
# 	python3 ./throughput_average.py
# 	python3 ./throughput_ratio.py
# 	python3 ./throughput_ratio_average.py
# 	python3 ./packetloss.py
# 	python3 ./averagepacketloss.py