all: energy

energy: ma mah mahAverage mahRatio mahRatioAverage

mahAverage:
	python3 ./mahBargraphAverage.py

mah:
	python3 ./mahBargraph.py

ma:
	python3 ./maBargraph.py

mahRatio:
	python3 ./mahRatio.py

mahRatioAverage:
	python3 ./mahRatioAverage.py

network: tp tpAvg

tp:
	python3 ./throughput.py

tpAvg:
	python3 ./throughputAverage.py

# throughput:
# 	python3 ./throughput.py
# 	python3 ./throughput_average.py
# 	python3 ./throughput_ratio.py
# 	python3 ./throughput_ratio_average.py
# 	python3 ./packetloss.py
# 	python3 ./averagepacketloss.py